# Generated by Django 5.2.1 on 2025-11-16 00:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('type', models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('REFACTOR', 'Refactor')], default='FEATURE', max_length=16)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HIGH', 'High')], default='MED', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PAUSED', 'Paused'), ('DONE', 'Done')], default='OPEN', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('switch_count', models.PositiveIntegerField(default=0)),
                ('last_switch_at', models.DateTimeField(blank=True, null=True)),
                ('total_focus_minutes', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('DAILY', 'Daily'), ('SESSION', 'Session')], max_length=16)),
                ('payload', models.JSONField()),
                ('dev_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='core.devsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MAIN', 'Main'), ('SIDE', 'Side')], default='MAIN', max_length=8)),
                ('dev_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tasks', to='core.devsession')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_tasks', to='core.task')),
            ],
            options={
                'unique_together': {('dev_session', 'task')},
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PR', 'Pull Request'), ('ISSUE', 'Issue / Ticket'), ('DOC', 'Documentation'), ('ARTICLE', 'Article'), ('TOOL', 'Tool'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('dev_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='core.devsession')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_links', to='core.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='devsession',
            name='tasks',
            field=models.ManyToManyField(related_name='sessions', through='core.SessionTask', to='core.task'),
        ),
        migrations.CreateModel(
            name='ContextSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('INTERRUPT', 'Interrupt'), ('QUICK_FIX', 'Quick fix'), ('MEETING', 'Meeting'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dev_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='context_switches', to='core.devsession')),
                ('from_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches_from', to='core.task')),
                ('to_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='switches_to', to='core.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
